sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '4'
before_install:
- npm i -g npm@^2.0.0
before_script:
- npm prune
after_success:
- npm run semantic-release
branches:
  only:
  - master
env:
  global:
    secure: PZq4kosH7RQhfzqYMT4VrwHamrna33TWbE2v3wyp53gm5kYThGFw4g/3tTfrDwyMon38FexLUJJoDnxQN8+Uvhboi1R5Lf2m7FRORroGa0+Q/uQQFkCP9ML7iPnGHqyu4KB1ENd0pl/yPGIJNElvvvmcqAk9/dw3fIo8YzPP8Gt9z3dB0igkQsVa1JyDL3jHDGk59i/MhcnHfEgu4OSAdR/9KL78iEISmIzbd6cHwGOlyuZ6DT0gT333j6cF/CgreTKk9xmq35yVnieZoT8PklBYy5pm9hVx2ioUNAgetyWiIhMtLksgxH12807p8POdtUDEV+O9i7mmj6/MqjtDNVnZZQE9ReUkojY2ks+OiamIWB9R6GU/70cVX9hpAOa6Vi14Ti8F1TYF0N/TAOlhrcT6R1jP7whiManSfaQxjyJBbgogTGFXlbepPp+zsa+FnhqfJgak3gXGYsUsNqIrWB7uJtL708gkV1+32nqKH21fI81/FBLfFywQ7V45F7aJPucyTyIo9oKTccZW8kLZHS1Zomib5y/XxXX4b/s8Ufm3AlBeH98PzYxtM2DNIjUj7BFoVXlir7CbZZrWfwLQtQY6OTgF7K7qW6+lk4VlqVAGGQe+eSiQn4B9Mrg2Si9jdw3yDk33VGzPSCe68p433OolhZUC4kg92wCWhlf/bqg=
