sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '4'
before_install:
- npm i -g npm@^2.0.0
before_script:
- npm prune
after_success:
- npm run semantic-release
branches:
  only:
  - master
env:
  global:
    secure: G2pRpCQAcR4T2kOpJy/qnvoNaSHfdT5IZelMcIVUcdjuLlVJG4vopPM+vjP/WHkMm8iBU/BspEis3TcAlVl4F3kgUmL4Z3jfkZhRVeMKq0+0krG7YYGEs2Xnmh56StMX6tkBj0GQhM7tMf1yVDB4crTEg+BaB74mn8Lyh7mjGBOfFW7xVwGu9WoMXZniyrr1VOlrdvx3Mn9MuBLHP6NqhRv96Z0gzUIXgot7jZAm4nATKmMLwnhPJGMMC3nFgnVmnFV2czgadggvmgGfRaU2OrjGMUMi/+MtiuDZs2ZIN7/wa96HGnqp5Xt85nP6aR28GIyHaMIWQbn5WB8ncYvxkoIEfPODI5xAwCbtuVr9ydPeOOkwtR+qnN+3kt32QdJaNS9FhHuvd8Y8ojEF0F92sNDTuQbsrXTeuEex3GJ3sUYMNIpdfbFU3Mc57P2Ufl/HiTiIpPT1MphroZlSRuTO9YjDwzCg9wdGtczeBexdpvPMshiXtfRL/QpXUwXufVuHoMSIsIy5NIm80ROqK1j+nPeZIj14G5EoLAKWjguB3NCIOK99wPnB9PRmrdBV9/MVnBsPSMXyUWlhn1bpqTW2Bf4ZV8yxVxEF2e1xEQwgtDnYyJi556p74WiNJpiEVAsXIYtqMTMS5axnEqpy9UzxSaoid9KyOWTMA8yU2vyNutQ=
